### ISSUE TITLE
请问meta中的val.txt的内容格式是什么？

### ISSUE THREAD

**Issue by zhongqiu1245** [Ai-Light/lumbar#1]
请问meta中的val.txt的内容格式含义是什么？是第一行对应val中第一张图片，之后第一行的写的内容代表val第一张图片所属的类别么？还是其他意思？谢谢

**Comment by Ai-Light** [comment]
那个是按coco2017的数据格式  具体可参考coco2017的数据格式



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： Draw <notifications@github.com>
日期: 2020/10/25 19:09 (GMT+08:00)
收件人： Ai-Light/lumbar <lumbar@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [Ai-Light/lumbar] 请问meta中的val.txt的内容格式是什么？ (#1)


请问meta中的val.txt的内容格式含义是什么？是第一行对应val中第一张图片，之后第一行的写的内容代表val第一张图片所属的类别么？还是其他意思？谢谢

―

**Comment by zhongqiu1245** [comment]
coco2017也没有val.txt啊,他的主文件不是json吗？
请问大神，您是否方便讲述一下您的val.txt是的内容如何设置的，或者是否方便分享一下您的val.txt文档吗？
不胜感激

**Comment by Ai-Light** [comment]
我中午发给你



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： Draw <notifications@github.com>
日期: 2020/10/26 07:11 (GMT+08:00)
收件人： Ai-Light/lumbar <lumbar@noreply.github.com>
抄送： ai-light <ai-light@outlook.com>, Comment <comment@noreply.github.com>
主题： Re: [Ai-Light/lumbar] 请问meta中的val.txt的内容格式是什么？ (#1)


coco2017也没有val.txt啊,他的主文件不是json吗？
请问大神，您是否方便讲述一下您的val.txt是的内容如何设置的，或者是否方便分享一下您的val.txt文档吗？
不胜感激

―

**Comment by zhongqiu1245** [comment]
谢谢！
zhongqiu1245@126.com
再次感谢！

**Comment by zhongqiu1245** [comment]
我指的是您的mmclasification的meta的val.txt，抱歉我刚才没说清

**Comment by zhongqiu1245** [comment]
请问您发了么？我一直在等候您的

**Comment by Ai-Light** [comment]
没收到么  我下午就发了  我查一下  稍等



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： Draw <notifications@github.com>
日期: 2020/10/26 18:35 (GMT+08:00)
收件人： Ai-Light/lumbar <lumbar@noreply.github.com>
抄送： ai-light <ai-light@outlook.com>, Comment <comment@noreply.github.com>
主题： Re: [Ai-Light/lumbar] 请问meta中的val.txt的内容格式是什么？ (#1)


请问您发了么？我一直在等候您的

―

**Comment by zhongqiu1245** [comment]
没有收到，还望您查一下

**Comment by Ai-Light** [comment]
我刚又发了一遍



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： Draw <notifications@github.com>
日期: 2020/10/26 18:53 (GMT+08:00)
收件人： Ai-Light/lumbar <lumbar@noreply.github.com>
抄送： ai-light <ai-light@outlook.com>, Comment <comment@noreply.github.com>
主题： Re: [Ai-Light/lumbar] 请问meta中的val.txt的内容格式是什么？ (#1)


没有收到，还望您查一下

―

**Comment by Ai-Light** [comment]
我发这个不是终究的数据  不过val是这样的格式  前面是图片  后面是类别



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： Draw <notifications@github.com>
日期: 2020/10/26 18:53 (GMT+08:00)
收件人： Ai-Light/lumbar <lumbar@noreply.github.com>
抄送： ai-light <ai-light@outlook.com>, Comment <comment@noreply.github.com>
主题： Re: [Ai-Light/lumbar] 请问meta中的val.txt的内容格式是什么？ (#1)


没有收到，还望您查一下

―

**Comment by zhongqiu1245** [comment]
收到，谢谢您



在 2020-10-26 18:54:59，"ai-light" <notifications@github.com> 写道：

我发这个不是终究的数据 不过val是这样的格式 前面是图片 后面是类别



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： Draw <notifications@github.com>
日期: 2020/10/26 18:53 (GMT+08:00)
收件人： Ai-Light/lumbar <lumbar@noreply.github.com>
抄送： ai-light <ai-light@outlook.com>, Comment <comment@noreply.github.com>
主题： Re: [Ai-Light/lumbar] 请问meta中的val.txt的内容格式是什么？ (#1)


没有收到，还望您查一下

―

**Comment by zhongqiu1245** [comment]
如果类别是cat,dog......什么的是不是就把0，1......那写数字改成cat，dog......？

**Comment by Ai-Light** [comment]
好像是数字对应  你查一下  我现在在外面 我早上说错了  应该是imagenet不是coco



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： Draw <notifications@github.com>
日期: 2020/10/26 19:01 (GMT+08:00)
收件人： Ai-Light/lumbar <lumbar@noreply.github.com>
抄送： ai-light <ai-light@outlook.com>, Comment <comment@noreply.github.com>
主题： Re: [Ai-Light/lumbar] 请问meta中的val.txt的内容格式是什么？ (#1)


如果类别是cat,dog......什么的是不是就把0，1......那写数字改成cat，dog......？

―

**Comment by zhongqiu1245** [comment]
请问大神您的meta文件夹中只放了一个val.txt对吗？

**Comment by Ai-Light** [comment]
应该是的



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： Draw <notifications@github.com>
日期: 2020/10/26 21:33 (GMT+08:00)
收件人： Ai-Light/lumbar <lumbar@noreply.github.com>
抄送： ai-light <ai-light@outlook.com>, Comment <comment@noreply.github.com>
主题： Re: [Ai-Light/lumbar] 请问meta中的val.txt的内容格式是什么？ (#1)


请问大神您的meta文件夹中只放了一个val.txt对吗？

―

**Comment by zhongqiu1245** [comment]
那么大神您的train文件夹下的子文件夹名称也是类别ID吧？跟val.txt中的类别数字完全一一致？（就是如果val.txt中有一张图片后面跟的类别数字为0，那这个0对应在train文件夹下一定有一个名称为0的子文件夹？）

**Comment by Ai-Light** [comment]
对



发送自我的三星盖乐世智能手机。



-------- 原始信息 --------
发件人： Draw <notifications@github.com>
日期: 2020/10/26 23:27 (GMT+08:00)
收件人： Ai-Light/lumbar <lumbar@noreply.github.com>
抄送： ai-light <ai-light@outlook.com>, Comment <comment@noreply.github.com>
主题： Re: [Ai-Light/lumbar] 请问meta中的val.txt的内容格式是什么？ (#1)


那么大神您的train文件夹下的子文件夹名称也是类别ID吧？跟val.txt中的类别数字完全一一致？（就是如果val.txt中有一张图片后面跟的类别数字为0，那这个0对应在train文件夹下一定有一个名称为0的子文件夹？）

―

**Comment by zhongqiu1245** [comment]
谢谢您的指导，感激不尽
